# Generated by Django 4.2.7 on 2023-11-24 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer_engineering_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Division', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Computer_engineering_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Division', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Computer_engineering_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Division', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Computer_engineering_4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Division', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cyber_security_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('Division', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(choices=[('الكترونيك عملي', 'الكترونيك عملي'), ('الكترونيك نظري', 'الكترونيك نظري'), ('انكليزي', 'انكليزي'), ('رياضيات', 'رياضيات'), ('شبكات', 'شبكات')], max_length=255)),
                ('lab_name', models.CharField(max_length=255)),
                ('attendance_time', models.DateTimeField()),
                ('department', models.CharField(blank=True, choices=[('Cyber_security_1', 'Cyber_security_1'), ('Computer_engineering_1', 'Computer_engineering_1'), ('Computer_engineering_2', 'Computer_engineering_2'), ('Computer_engineering_3', 'Computer_engineering_3'), ('Computer_engineering_3', 'Computer_engineering_4')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Cyber_security_1Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True)),
                ('lecture_name', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lecture')),
                ('student', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myapp.cyber_security_1')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerEngineering_4Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True)),
                ('lecture_name', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lecture')),
                ('student', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myapp.computer_engineering_4')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerEngineering_3Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True)),
                ('lecture_name', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lecture')),
                ('student', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myapp.computer_engineering_3')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerEngineering_2Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True)),
                ('lecture_name', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lecture')),
                ('student', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myapp.computer_engineering_2')),
            ],
        ),
        migrations.CreateModel(
            name='ComputerEngineering_1Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True)),
                ('lecture_name', models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.lecture')),
                ('student', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='myapp.computer_engineering_1')),
            ],
        ),
    ]
