# Generated by Django 4.2.7 on 2023-11-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_name', models.CharField(choices=[('الكترونيك عملي', 'الكترونيك عملي'), ('الكترونيك نظري', 'الكترونيك نظري'), ('انكليزي', 'انكليزي'), ('رياضيات', 'رياضيات'), ('شبكات', 'شبكات')], max_length=255)),
                ('lab_name', models.CharField(max_length=255)),
                ('attendance_time', models.DateTimeField()),
                ('department', models.CharField(blank=True, choices=[('Cyber_security_1', 'Cyber_security_1'), ('Computer_engineering_1', 'Computer_engineering_1'), ('Computer_engineering_2', 'Computer_engineering_2'), ('Computer_engineering_3', 'Computer_engineering_3'), ('Computer_engineering_3', 'Computer_engineering_4')], max_length=40)),
            ],
        ),
    ]
