# Generated by Django 4.2.7 on 2023-11-25 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_cyber_security_1request_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cyber_security_11Request',
        ),
    ]
