# Generated by Django 4.2.7 on 2023-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_computerengineering_1request_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerengineering_2request',
            name='chair',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='Pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='computerengineering_3request',
            name='chair',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='Pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='computerengineering_4request',
            name='chair',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='Pending', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cyber_security_1request',
            name='chair',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12')], default='Pending', max_length=10, null=True),
        ),
    ]
