# Generated by Django 4.2.7 on 2023-11-25 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_computer_engineering_32_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computerengineering_332request',
            name='name',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.computerengineering_32request'),
        ),
    ]
