# Generated by Django 4.2.7 on 2023-12-12 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_computer_engineering_42_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cyber_security_11request',
            name='name',
        ),
        migrations.AddField(
            model_name='cyber_security_11request',
            name='student',
            field=models.ForeignKey(default=1, max_length=50, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='myapp.cyber_security_1request'),
            preserve_default=False,
        ),
    ]
