# Generated by Django 4.2.7 on 2024-02-07 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_cyber_security_11request_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerengineering_11request',
            name='status',
        ),
    ]
