# Generated by Django 4.2.7 on 2024-02-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_computerengineering_11request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerengineering_11request',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, null=True),
        ),
    ]
