# Generated by Django 4.2.7 on 2024-02-08 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_computerengineering_11request_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerengineering_11request',
            name='name',
        ),
        migrations.AddField(
            model_name='computerengineering_11request',
            name='chair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.computerengineering_1request'),
        ),
    ]
