# Generated by Django 4.2.7 on 2024-02-08 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_computerengineering_11request_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerengineering_11request',
            name='chair',
        ),
        migrations.AddField(
            model_name='computerengineering_11request',
            name='name',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.computerengineering_1request'),
        ),
    ]
