# Generated by Django 4.2.7 on 2024-02-08 01:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_remove_computerengineering_11request_chair_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computerengineering_11request',
            name='chair',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chair_request', to='myapp.computerengineering_1request'),
        ),
        migrations.AlterField(
            model_name='computerengineering_11request',
            name='name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_requests', to='myapp.computerengineering_1request'),
        ),
    ]
