# Generated by Django 4.2.7 on 2024-02-08 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_computerengineering_11request_chair_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computerengineering_11request',
            name='chair',
        ),
    ]
